# Author: Satish Ch@uhan

"""
SQL Server schema export utilities for schema comparison and script generation.
Provides the same API as src.backup.exporters so schema_tab and script generator work without external src package.
"""
from collections import namedtuple
from typing import Any, List, Optional, Tuple
import logging

# --- Simple helpers (replacing src.utils.sql and src.utils.paths) ---

def sql_header() -> str:
    """Return a standard header comment for generated SQL scripts."""
    return "-- Generated by Azure Migration Tool - Schema export\n"

def qident(name: str) -> str:
    """Quote SQL Server identifier: [name]. Handles ] in name by doubling."""
    if name is None:
        return "[]"
    s = str(name).replace("]", "]]")
    return f"[{s}]"


def type_sql(type_name: str, max_length: int, precision: int, scale: int) -> str:
    """Build SQL type string from column metadata."""
    t = type_name.lower()
    if t in ("varchar", "nvarchar", "char", "nchar", "varbinary", "binary"):
        length = "MAX" if max_length == -1 else str(max_length)
        return f"{type_name}({length})"
    if t in ("decimal", "numeric"):
        return f"{type_name}({precision},{scale})"
    if t in ("datetime2", "datetimeoffset", "time"):
        return f"{type_name}({scale})"
    if t == "float" and precision and precision != 53:
        return f"float({precision})"
    return type_name


def parse_int_or_default(s, default: int) -> int:
    """Parse integer or return default."""
    if s is None:
        return default
    s = str(s).strip()
    if not s:
        return default
    try:
        return int(float(s))
    except Exception:
        return default


# --- Named tuples for return types ---

TableRef = namedtuple("TableRef", ["schema_name", "table_name"])
ColumnInfo = namedtuple(
    "ColumnInfo",
    [
        "column_name",
        "data_type",
        "character_maximum_length",
        "numeric_precision",
        "numeric_scale",
        "is_nullable",
        "column_id",
        "collation_name",
    ],
    defaults=(None,),
)
TriggerInfo = namedtuple("TriggerInfo", ["schema_name", "trigger_name", "table_name", "object_id"])
SequenceInfo = namedtuple("SequenceInfo", [
    "schema_name", "sequence_name", "start_value", "increment", "minimum_value",
    "maximum_value", "is_cycling", "cache_size"
])
SynonymInfo = namedtuple("SynonymInfo", ["schema_name", "synonym_name", "base_object_name"])


def fetch_tables(cur) -> List[TableRef]:
    """Return list of (schema_name, table_name) for user tables."""
    cur.execute("""
        SELECT s.name, t.name
        FROM sys.tables t
        INNER JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE t.is_ms_shipped = 0
        ORDER BY s.name, t.name
    """)
    return [TableRef(row[0], row[1]) for row in cur.fetchall()]


def fetch_columns(cur, schema_name: str, table_name: str) -> List[ColumnInfo]:
    """Return column list for a table. Used by build_create_table_sql."""
    cur.execute("""
        SELECT c.name, t.name AS type_name,
               c.max_length, c.precision, c.scale, c.is_nullable, c.column_id,
               CAST(COALESCE(
                   CAST(c.collation_name AS NVARCHAR(256)),
                   CASE WHEN t.name IN (
                       N'varchar', N'nvarchar', N'char', N'nchar', N'text', N'ntext'
                   )
                   THEN CONVERT(NVARCHAR(256), DATABASEPROPERTYEX(DB_NAME(), N'Collation'))
                   ELSE NULL END
               ) AS NVARCHAR(256)) AS collation_name
        FROM sys.columns c
        INNER JOIN sys.types t ON t.user_type_id = c.user_type_id
        INNER JOIN sys.tables tab ON tab.object_id = c.object_id
        INNER JOIN sys.schemas s ON s.schema_id = tab.schema_id
        WHERE s.name = ? AND tab.name = ?
        ORDER BY c.column_id
    """, (schema_name, table_name))
    rows = cur.fetchall()
    out = []
    for r in rows:
        # Map type name and max_length to character_maximum_length (for varchar/nchar)
        char_max = None
        if r[1] in ("varchar", "nvarchar", "char", "nchar", "binary", "varbinary"):
            char_max = r[2] if r[1].startswith("n") else r[2]  # n* is length in chars for nvarchar
        raw_coll = r[7] if len(r) > 7 else None
        if raw_coll is not None and hasattr(raw_coll, "strip"):
            raw_coll = raw_coll.strip() or None
        out.append(
            ColumnInfo(
                column_name=r[0],
                data_type=r[1],
                character_maximum_length=char_max if char_max is not None else r[2],
                numeric_precision=r[3],
                numeric_scale=r[4],
                is_nullable=bool(r[5]),
                column_id=r[6],
                collation_name=raw_coll,
            )
        )
    return out


def fetch_primary_key(cur, schema_name: str, table_name: str) -> Optional[List[str]]:
    """Return list of column names that form the primary key, or None if no PK."""
    cur.execute("""
        SELECT c.name
        FROM sys.index_columns ic
        INNER JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
        INNER JOIN sys.indexes i ON i.object_id = ic.object_id AND i.index_id = ic.index_id
        INNER JOIN sys.tables t ON t.object_id = i.object_id
        INNER JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE s.name = ? AND t.name = ? AND i.is_primary_key = 1
        ORDER BY ic.key_ordinal
    """, (schema_name, table_name))
    rows = cur.fetchall()
    if not rows:
        return None
    return [r[0] for r in rows]


def fetch_objects(cur, type_filter: str) -> List[Tuple]:
    """Return list of (schema_name, object_name, type_desc, object_id) for views/procs/functions.
    type_filter: 'V' views, 'P' procedures, 'FN,TF,IF' functions.
    """
    types = [t.strip() for t in type_filter.split(",")]
    placeholders = ",".join("?" for _ in types)
    cur.execute(f"""
        SELECT s.name, o.name, o.type_desc, o.object_id
        FROM sys.objects o
        INNER JOIN sys.schemas s ON s.schema_id = o.schema_id
        WHERE o.type IN ({placeholders}) AND o.is_ms_shipped = 0
        ORDER BY s.name, o.name
    """, types)
    return list(cur.fetchall())


def fetch_triggers(cur) -> List[TriggerInfo]:
    """Return list of trigger info (schema_name, trigger_name, table_name, object_id)."""
    cur.execute("""
        SELECT OBJECT_SCHEMA_NAME(tr.parent_id), tr.name, 
               OBJECT_SCHEMA_NAME(tr.parent_id) + '.' + OBJECT_NAME(tr.parent_id), tr.object_id
        FROM sys.triggers tr
        WHERE tr.is_ms_shipped = 0 AND tr.parent_id > 0
    """)
    return [TriggerInfo(row[0], row[1], row[2], row[3]) for row in cur.fetchall()]


def fetch_sequences(cur) -> List[SequenceInfo]:
    """Return list of sequence info."""
    cur.execute("""
        SELECT SCHEMA_NAME(s.schema_id), s.name,
               start_value, increment, minimum_value, maximum_value,
               is_cycling, cache_size
        FROM sys.sequences s
    """)
    return [
        SequenceInfo(
            schema_name=row[0], sequence_name=row[1],
            start_value=row[2], increment=row[3], minimum_value=row[4], maximum_value=row[5],
            is_cycling=bool(row[6]), cache_size=row[7]
        )
        for row in cur.fetchall()
    ]


def fetch_synonyms(cur) -> List[SynonymInfo]:
    """Return list of synonym info."""
    cur.execute("""
        SELECT SCHEMA_NAME(s.schema_id), s.name, base_object_name
        FROM sys.synonyms s
    """)
    return [SynonymInfo(row[0], row[1], row[2]) for row in cur.fetchall()]


def object_definition(cur, object_id: int) -> Optional[str]:
    """Return T-SQL definition for a view/procedure/function/trigger."""
    cur.execute("SELECT OBJECT_DEFINITION(?)", (object_id,))
    row = cur.fetchone()
    return row[0] if row and row[0] else None


def _obj_name(cur, object_id: int) -> str:
    """Return [schema].[name] for an object_id."""
    cur.execute("SELECT SCHEMA_NAME(schema_id), name FROM sys.objects WHERE object_id = ?", (object_id,))
    row = cur.fetchone()
    if not row:
        return ""
    return f"{qident(row[0])}.{qident(row[1])}"


def export_primary_keys(cur) -> str:
    """Export all primary key constraints as ALTER TABLE ... ADD CONSTRAINT."""
    cur.execute("""
        SELECT i.name, t.object_id, s.name, OBJECT_NAME(t.object_id)
        FROM sys.indexes i
        INNER JOIN sys.tables t ON t.object_id = i.object_id
        INNER JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE i.is_primary_key = 1 AND t.is_ms_shipped = 0
    """)
    lines = []
    for idx_name, obj_id, sch, tbl in cur.fetchall():
        cur.execute("""
            SELECT c.name FROM sys.index_columns ic
            INNER JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
            WHERE ic.object_id = ? AND ic.index_id = (SELECT index_id FROM sys.indexes WHERE object_id = ? AND is_primary_key = 1)
            ORDER BY ic.key_ordinal
        """, (obj_id, obj_id))
        cols = [qident(r[0]) for r in cur.fetchall()]
        if cols:
            lines.append(f"ALTER TABLE {qident(sch)}.{qident(tbl)} ADD CONSTRAINT {qident(idx_name)} PRIMARY KEY ({', '.join(cols)});")
    return "\n".join(lines) + ("\n" if lines else "")


def export_foreign_keys(cur, logger: Optional[logging.Logger] = None) -> Tuple[str, Any]:
    """Export foreign key constraints. Returns (sql_string, metadata)."""
    cur.execute("""
        SELECT fk.name, OBJECT_SCHEMA_NAME(fk.parent_object_id), OBJECT_NAME(fk.parent_object_id),
               OBJECT_SCHEMA_NAME(fk.referenced_object_id), OBJECT_NAME(fk.referenced_object_id),
               fk.delete_referential_action_desc, fk.update_referential_action_desc
        FROM sys.foreign_keys fk
    """)
    lines = []
    for fk_name, p_sch, p_tbl, r_sch, r_tbl, del_action, upd_action in cur.fetchall():
        cur.execute("""
            SELECT COL_NAME(fkc.parent_object_id, fkc.parent_column_id),
                   COL_NAME(fkc.referenced_object_id, fkc.referenced_column_id)
            FROM sys.foreign_key_columns fkc
            WHERE fkc.constraint_object_id = OBJECT_ID(?)
            ORDER BY fkc.constraint_column_id
        """, (f"{p_sch}.{fk_name}",))
        pairs = cur.fetchall()
        if not pairs:
            continue
        pc = ", ".join(qident(p[0]) for p in pairs)
        rc = ", ".join(qident(p[1]) for p in pairs)
        on_del = " ON DELETE " + del_action.replace("_", " ") if del_action != "NO_ACTION" else ""
        on_upd = " ON UPDATE " + upd_action.replace("_", " ") if upd_action != "NO_ACTION" else ""
        lines.append(
            f"ALTER TABLE {qident(p_sch)}.{qident(p_tbl)} "
            f"ADD CONSTRAINT {qident(fk_name)} FOREIGN KEY ({pc}) "
            f"REFERENCES {qident(r_sch)}.{qident(r_tbl)} ({rc}){on_del}{on_upd};"
        )
    return "\n".join(lines) + ("\n" if lines else ""), None


def export_check_constraints(cur) -> str:
    """Export check constraints."""
    cur.execute("""
        SELECT cc.name, OBJECT_SCHEMA_NAME(cc.parent_object_id), OBJECT_NAME(cc.parent_object_id), cc.definition
        FROM sys.check_constraints cc
    """)
    lines = []
    for name, sch, tbl, defn in cur.fetchall():
        if defn:
            lines.append(f"ALTER TABLE {qident(sch)}.{qident(tbl)} ADD CONSTRAINT {qident(name)} CHECK {defn};")
    return "\n".join(lines) + ("\n" if lines else "")


def export_default_constraints(cur) -> str:
    """Export default constraints."""
    cur.execute("""
        SELECT dc.name, OBJECT_SCHEMA_NAME(dc.parent_object_id), OBJECT_NAME(dc.parent_object_id),
               c.name, dc.definition
        FROM sys.default_constraints dc
        INNER JOIN sys.columns c ON c.object_id = dc.parent_object_id AND c.column_id = dc.parent_column_id
    """)
    lines = []
    for dc_name, sch, tbl, col, defn in cur.fetchall():
        if defn:
            lines.append(f"ALTER TABLE {qident(sch)}.{qident(tbl)} ADD CONSTRAINT {qident(dc_name)} DEFAULT {defn} FOR {qident(col)};")
    return "\n".join(lines) + ("\n" if lines else "")


def export_indexes(cur, logger: Optional[logging.Logger] = None) -> Tuple[str, Any]:
    """Export non-PK indexes. Returns (sql_string, metadata)."""
    cur.execute("""
        SELECT i.name, i.object_id, i.is_unique, i.type_desc,
               s.name, OBJECT_NAME(i.object_id)
        FROM sys.indexes i
        INNER JOIN sys.tables t ON t.object_id = i.object_id
        INNER JOIN sys.schemas s ON s.schema_id = t.schema_id
        WHERE i.is_primary_key = 0 AND i.type > 0 AND t.is_ms_shipped = 0
    """)
    lines = []
    for idx_name, obj_id, is_unique, type_desc, sch, tbl in cur.fetchall():
        cur.execute("""
            SELECT c.name, ic.is_descending_key
            FROM sys.index_columns ic
            INNER JOIN sys.columns c ON c.object_id = ic.object_id AND c.column_id = ic.column_id
            WHERE ic.object_id = ? AND ic.index_id = (SELECT index_id FROM sys.indexes WHERE object_id = ? AND name = ?)
            ORDER BY ic.key_ordinal
        """, (obj_id, obj_id, idx_name))
        cols = cur.fetchall()
        if not cols:
            continue
        col_list = ", ".join(qident(r[0]) + (" DESC" if r[1] else " ASC") for r in cols)
        uniq = " UNIQUE " if is_unique else " "
        lines.append(f"CREATE{uniq}{type_desc} INDEX {qident(idx_name)} ON {qident(sch)}.{qident(tbl)} ({col_list});")
    return "\n".join(lines) + ("\n" if lines else ""), None


def _column_sql(col: ColumnInfo) -> str:
    """Build single column definition for CREATE TABLE."""
    typ = col.data_type
    if typ in ("varchar", "nvarchar", "char", "nchar", "varbinary", "binary"):
        length = col.character_maximum_length or 1
        if typ.startswith("n"):
            length = length // 2  # max_length is bytes for nvarchar
        if length == -1:
            length = "MAX"
        typ = f"{typ}({length})"
    elif typ in ("decimal", "numeric"):
        p, s = col.numeric_precision or 18, col.numeric_scale or 0
        typ = f"{typ}({p},{s})"
    elif typ in ("datetime2", "time"):
        s = col.numeric_scale or 7
        typ = f"{typ}({s})"
    dt = (col.data_type or "").lower()
    coll = getattr(col, "collation_name", None)
    if coll is not None and hasattr(coll, "strip"):
        coll = coll.strip() or None
    if coll and dt in ("varchar", "nvarchar", "char", "nchar", "text", "ntext"):
        typ = f"{typ} COLLATE {coll}"
    null = " NULL" if col.is_nullable else " NOT NULL"
    return f"{qident(col.column_name)} {typ}{null}"


def build_create_table_sql(schema_name: str, table_name: str, cols: List[ColumnInfo],
                            pk_columns: Optional[List[str]], include_pk: bool = True) -> str:
    """Build CREATE TABLE statement. pk_columns is list of column names for PK."""
    col_defs = [_column_sql(c) for c in cols]
    if include_pk and pk_columns:
        col_defs.append(f"PRIMARY KEY ({', '.join(qident(c) for c in pk_columns)})")
    body = ",\n    ".join(col_defs)
    return f"CREATE TABLE {qident(schema_name)}.{qident(table_name)} (\n    {body}\n);"


def wrap_create_or_alter(schema_name: str, object_name: str, definition: Optional[str], obj_type: str) -> str:
    """Wrap object definition with IF NOT EXISTS / DROP + CREATE or ALTER."""
    if not definition:
        return f"-- No definition for {qident(schema_name)}.{qident(object_name)}\n"
    full = f"{qident(schema_name)}.{qident(object_name)}"
    if obj_type.upper() == "VIEW":
        return f"IF OBJECT_ID('{full}', 'V') IS NOT NULL DROP VIEW {full};\nGO\n{definition}\nGO\n"
    if obj_type.upper() in ("PROC", "P"):
        return f"IF OBJECT_ID('{full}', 'P') IS NOT NULL DROP PROCEDURE {full};\nGO\n{definition}\nGO\n"
    if obj_type.upper() in ("FUNCTION", "FN", "TF", "IF"):
        return f"IF OBJECT_ID('{full}') IS NOT NULL DROP FUNCTION {full};\nGO\n{definition}\nGO\n"
    if obj_type.upper() == "TRIGGER":
        return f"IF OBJECT_ID('{full}', 'TR') IS NOT NULL DROP TRIGGER {full};\nGO\n{definition}\nGO\n"
    return definition + "\nGO\n"


def export_sequences(cur) -> str:
    """Export all sequences as CREATE SEQUENCE (for full export)."""
    seqs = fetch_sequences(cur)
    out = []
    for seq in seqs:
        full = f"{qident(seq.schema_name)}.{qident(seq.sequence_name)}"
        out.append(f"CREATE SEQUENCE {full} AS BIGINT")
        if seq.start_value is not None:
            out.append(f"    START WITH {seq.start_value}")
        if seq.increment is not None:
            out.append(f"    INCREMENT BY {seq.increment}")
        out.append("GO")
    return "\n".join(out) + "\n" if out else ""


def export_synonyms(cur) -> str:
    """Export all synonyms (for full export)."""
    syns = fetch_synonyms(cur)
    out = []
    for s in syns:
        full = f"{qident(s.schema_name)}.{qident(s.synonym_name)}"
        out.append(f"CREATE SYNONYM {full} FOR {s.base_object_name};")
        out.append("GO")
    return "\n".join(out) + "\n" if out else ""
